tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  _args_: ["${model.main._args_[0]}"]
  token: ${oc.env:HF_TOKEN}
  trust_remote_code: true

kwargs:
  padding_side: left
  truncation_side: left
