tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  _args_: ["transhumanist-already-exists/tereshchenkoblue-tokenizer"]
  token: ${oc.env:HF_TOKEN}
  trust_remote_code: true

kwargs:
  padding_side: left
  truncation_side: left
