# Test training configuration for quick validation using Hydra instantiate
_target_: transformers.TrainingArguments
output_dir: outputs
seed: 42
max_steps: 5
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
learning_rate: 5e-5
weight_decay: 0.0
warmup_ratio: 0.1
lr_scheduler_type: cosine
gradient_checkpointing: true
dataloader_num_workers: 1
bf16: true
gradient_accumulation_steps: 1

# Optimizer configuration
optim: adamw_torch

# Logging and evaluation configuration
logging_steps: 1
save_steps: 5
eval_strategy: steps
eval_steps: 2
