defaults:
  - _self_
  - hydra: default
  - data: kobza
  - model: gemma_3_270mb
  - tokenizer: auto
  - pretraining: default
  - data_processing: default
  - experiment_tracking: wandb

seed: 42
path_to_freeze_ids: data/freeze_ids_gemma_tereshchenko.joblib
