pretrain_config:
  _target_: transformers.TrainingArguments

  seed: 42

  # max_seq_length: 128
  # max_length: 2048
  # packing: false
  # eval_packing: false
  group_by_length: false
  dataloader_pin_memory: true

  max_steps: 5
  # loss_type: nll

  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false

  optim: adamw_torch_fused
  learning_rate: 2e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8

  max_grad_norm: 0.3
  warmup_ratio: 0.03
  weight_decay: 0.01
  lr_scheduler_type: cosine
  # lr_scheduler_kwargs:
  #   num_cycles: 1

  # fp16: true
  bf16: true
  # tf32: true

  # Logging and evaluation configuration\
  logging_steps: 1
  save_steps: 5
  eval_strategy: steps
  eval_steps: 2
  save_total_limit: 1
  eval_on_start: true

  push_to_hub: false

  dataloader_num_workers: 1
  dataloader_prefetch_factor: 1

  remove_unused_columns: false
  ddp_find_unused_parameters: false

  # dataset_kwargs:
  #   add_special_tokens: false
  #   append_concat_token: true
